### ISSUE TITLE
Update Poison dependency to ~> 3.0

### ISSUE THREAD

**Issue by premist** [sashaafm/gcloudex#7]
Poison 3.0 was [released](https://hex.pm/packages/poison/3.0.0) on October 2, 2016. We're currently overriding Poison dependency to `~> 3.0` in our mix.exs, but it'll be handy if gcloudex uses Poison 3.0.

**Comment by sashaafm** [comment]
Hello @premist, have you experimented GCloudex with Poison 3.0? I'll try a new branch sometime this weekend with the new version and I'll run the tests to see if there are any problems.

**Comment by sashaafm** [comment]
@premist I can't seem to be able to update to Poison 3.0 since Goth and JSON Web Token require Poison 2.1. Could you tell me how you overrode the dep in the mix file?

**Comment by premist** [comment]
Sorry for late reply, after few experiments I also concluded that it's quite hard to update the dependency. I downgraded my project's dep to Poison 2.1. 

Sorry for the confusion!
